"""内置20个经典PDE案例库"""
import numpy as np

PDE_LIBRARY = [
    {
        'id': 'heat_basic',
        'name': '1D热传导方程',
        'pde_type': 'heat',
        'n_dims': 1,
        'category': '抛物型',
        'description': '最基础的抛物型PDE，描述热传导与扩散过程',
        'equation_latex': r'\frac{\partial u}{\partial t} = \alpha \frac{\partial^2 u}{\partial x^2}',
        'params': {'alpha': 0.01},
        'domain': {'x': (0, 1), 't': (0, 1)},
        'ic_expression': 'sin(pi*x)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': 'u(x,t)=sin(πx)·exp(-απ²t)',
        'difficulty': '⭐',
        'default_epochs': 3000,
        'default_layers': [2, 64, 64, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'heat_gaussian',
        'name': '高斯脉冲扩散',
        'pde_type': 'heat',
        'n_dims': 1,
        'category': '抛物型',
        'description': '初始高斯脉冲在空间中的扩散过程',
        'equation_latex': r'\frac{\partial u}{\partial t} = 0.05 \frac{\partial^2 u}{\partial x^2}',
        'params': {'alpha': 0.05},
        'domain': {'x': (-1, 1), 't': (0, 1)},
        'ic_expression': 'exp(-50*(x-0.5)**2)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': False,
        'reference_solution': '',
        'difficulty': '⭐⭐',
        'default_epochs': 5000,
        'default_layers': [2, 128, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'wave_string',
        'name': '弦振动方程',
        'pde_type': 'wave',
        'n_dims': 1,
        'category': '双曲型',
        'description': '经典弦振动波动方程',
        'equation_latex': r'\frac{\partial^2 u}{\partial t^2} = c^2 \frac{\partial^2 u}{\partial x^2}',
        'params': {'c': 1.0},
        'domain': {'x': (0, 1), 't': (0, 1)},
        'ic_expression': 'sin(pi*x)',
        'ic_dt_expression': '0',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': 'u(x,t)=sin(πx)·cos(πct)',
        'difficulty': '⭐⭐',
        'default_epochs': 5000,
        'default_layers': [2, 128, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'wave_complex',
        'name': '多谐波驻波',
        'pde_type': 'wave',
        'n_dims': 1,
        'category': '双曲型',
        'description': '包含多个谐波的复杂初值，测试多尺度能力',
        'equation_latex': r'\frac{\partial^2 u}{\partial t^2} = \frac{\partial^2 u}{\partial x^2}',
        'params': {'c': 1.0},
        'domain': {'x': (0, 1), 't': (0, 2)},
        'ic_expression': 'sin(pi*x)+0.3*sin(3*pi*x)+0.1*sin(5*pi*x)',
        'ic_dt_expression': '0',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': '各谐波独立传播',
        'difficulty': '⭐⭐⭐',
        'default_epochs': 8000,
        'default_layers': [2, 256, 256, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'burgers_basic',
        'name': 'Burgers方程(无粘)',
        'pde_type': 'burgers',
        'n_dims': 1,
        'category': '非线性双曲',
        'description': '非线性对流扩散方程，激波形成测试',
        'equation_latex': r'\frac{\partial u}{\partial t} + u \frac{\partial u}{\partial x} = \nu \frac{\partial^2 u}{\partial x^2}',
        'params': {'nu': 0.01},
        'domain': {'x': (0, 1), 't': (0, 1)},
        'ic_expression': '-sin(pi*x)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': False,
        'reference_solution': 'Hopf-Cole变换',
        'difficulty': '⭐⭐⭐',
        'default_epochs': 10000,
        'default_layers': [2, 128, 256, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'burgers_viscous',
        'name': 'Burgers方程(高粘度)',
        'pde_type': 'burgers',
        'n_dims': 1,
        'category': '非线性双曲',
        'description': '高粘度Burgers，平滑解收敛',
        'equation_latex': r'u_t + u u_x = 0.1 u_{xx}',
        'params': {'nu': 0.1},
        'domain': {'x': (0, 1), 't': (0, 1)},
        'ic_expression': 'sin(2*pi*x)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': False,
        'reference_solution': '',
        'difficulty': '⭐⭐',
        'default_epochs': 5000,
        'default_layers': [2, 128, 128, 64, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'allen_cahn_doublewell',
        'name': 'Allen-Cahn方程',
        'pde_type': 'allen_cahn',
        'n_dims': 1,
        'category': '相场方程',
        'description': '材料科学相场模型，描述相分离过程',
        'equation_latex': r'\frac{\partial u}{\partial t} = \varepsilon^2 \Delta u + \gamma (u - u^3)',
        'params': {'epsilon': 0.01, 'gamma': 1.0},
        'domain': {'x': (0, 1), 't': (0, 1)},
        'ic_expression': '0.5*(x<0.6)-0.5',
        'bc_left_expression': '-1',
        'bc_right_expression': '1',
        'analytical_solution': False,
        'reference_solution': '行波解',
        'difficulty': '⭐⭐⭐',
        'default_epochs': 10000,
        'default_layers': [2, 128, 256, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'kdv_soliton',
        'name': 'KdV方程单孤子',
        'pde_type': 'kdv',
        'n_dims': 1,
        'category': '非线性色散',
        'description': 'Korteweg-de Vries方程，展示孤子传播',
        'equation_latex': r'\frac{\partial u}{\partial t} - 6 u \frac{\partial u}{\partial x} + \frac{\partial^3 u}{\partial x^3} = 0',
        'params': {'alpha': -6.0, 'beta': 1.0},
        'domain': {'x': (-1, 2), 't': (0, 1)},
        'ic_expression': '-2*(x>0)*(x<0.5)*exp(-20*(x-0.25)**2)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': 'u(x,t)=-2c·sech²(√c(x-4ct))',
        'difficulty': '⭐⭐⭐⭐',
        'default_epochs': 15000,
        'default_layers': [2, 256, 256, 128, 64, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'kdv_twosolitons',
        'name': 'KdV方程双孤子碰撞',
        'pde_type': 'kdv',
        'n_dims': 1,
        'category': '非线性色散',
        'description': '两个孤子的碰撞相互作用',
        'equation_latex': r'u_t - 6u u_x + u_{xxx} = 0',
        'params': {'alpha': -6.0, 'beta': 1.0},
        'domain': {'x': (-1, 3), 't': (0, 0.5)},
        'ic_expression': '-6*(4*exp(-2*(x-0.3)**2)+1.5*exp(-0.5*(x-1.5)**2))',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': '解析双孤子解',
        'difficulty': '⭐⭐⭐⭐⭐',
        'default_epochs': 20000,
        'default_layers': [2, 512, 512, 256, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'sine_gordon',
        'name': 'Sine-Gordon方程',
        'pde_type': 'sine_gordon',
        'n_dims': 1,
        'category': '相对论场论',
        'description': '量子场论和超导中的经典非线性波动方程',
        'equation_latex': r'\frac{\partial^2 u}{\partial t^2} - \frac{\partial^2 u}{\partial x^2} + \sin(u) = 0',
        'params': {'gamma': 1.0},
        'domain': {'x': (-5, 5), 't': (0, 2)},
        'ic_expression': '4*atan(exp(x))',
        'ic_dt_expression': '0',
        'bc_left_expression': '0',
        'bc_right_expression': '2*pi',
        'analytical_solution': True,
        'reference_solution': 'kink孤子解',
        'difficulty': '⭐⭐⭐⭐',
        'default_epochs': 15000,
        'default_layers': [2, 256, 256, 128, 1],
        'has_fdm_reference': False,
    },
    {
        'id': 'reaction_diffusion_gray_scott',
        'name': 'Gray-Scott反应扩散',
        'pde_type': 'reaction_diffusion',
        'n_dims': 1,
        'category': '数学生物学',
        'description': '非线性化学反应扩散系统，图灵斑图',
        'equation_latex': r'\dot{u}=D_1\Delta u - uv^2 + F(1-u), \dot{v}=D_2\Delta v + uv^2 - (F+k)v',
        'params': {'D1': 0.0001, 'D2': 0.00005, 'a': 0.04, 'b': 0.06},
        'domain': {'x': (0, 1), 't': (0, 10)},
        'ic_expression': '0.5+0.1*sin(2*pi*x)',
        'bc_left_expression': '0.5',
        'bc_right_expression': '0.5',
        'analytical_solution': False,
        'reference_solution': '',
        'difficulty': '⭐⭐⭐⭐',
        'default_epochs': 15000,
        'default_layers': [2, 256, 256, 128, 2],
        'has_fdm_reference': False,
    },
    {
        'id': 'schrodinger_soliton',
        'name': '非线性薛定谔方程',
        'pde_type': 'schrodinger',
        'n_dims': 1,
        'category': '量子力学',
        'description': 'NLS方程亮孤子解',
        'equation_latex': r'i \frac{\partial \psi}{\partial t} + \frac{1}{2}\frac{\partial^2 \psi}{\partial x^2} + |\psi|^2 \psi = 0',
        'params': {'sigma': 1.0},
        'domain': {'x': (-5, 5), 't': (0, 2)},
        'ic_expression': 'exp(-0.5*x**2)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': '亮孤子 ψ(x,t)=sech(x)·exp(-it/2)',
        'difficulty': '⭐⭐⭐⭐⭐',
        'default_epochs': 15000,
        'default_layers': [2, 256, 512, 256, 2],
        'has_fdm_reference': False,
    },
    {
        'id': 'poisson_basic',
        'name': '2D泊松方程',
        'pde_type': 'poisson',
        'n_dims': 2,
        'category': '椭圆型',
        'description': '二维静电学泊松方程',
        'equation_latex': r'- \alpha (\frac{\partial^2 u}{\partial x^2} + \frac{\partial^2 u}{\partial y^2}) = f(x,y)',
        'params': {'alpha': 1.0, 'f': 1.0},
        'domain': {'x': (0, 1), 'y': (0, 1), 't': (0, 1)},
        'ic_expression': '0',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'bc_bottom_expression': '0',
        'bc_top_expression': '0',
        'analytical_solution': False,
        'reference_solution': '',
        'difficulty': '⭐⭐',
        'default_epochs': 5000,
        'default_layers': [3, 64, 128, 64, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'poisson_irregular',
        'name': '泊松方程点源',
        'pde_type': 'poisson',
        'n_dims': 2,
        'category': '椭圆型',
        'description': '含高斯点源的2D泊松方程',
        'equation_latex': r'-\Delta u = \exp(-100((x-0.5)^2+(y-0.5)^2))',
        'params': {'alpha': 1.0},
        'domain': {'x': (0, 1), 'y': (0, 1), 't': (0, 1)},
        'ic_expression': '0',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'bc_bottom_expression': '0',
        'bc_top_expression': '0',
        'analytical_solution': False,
        'reference_solution': '',
        'difficulty': '⭐⭐⭐',
        'default_epochs': 8000,
        'default_layers': [3, 128, 128, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'advection_1d',
        'name': '线性对流方程',
        'pde_type': 'advection',
        'n_dims': 1,
        'category': '双曲型',
        'description': '标量线性传输方程，测试特征传播',
        'equation_latex': r'\frac{\partial u}{\partial t} + a \frac{\partial u}{\partial x} = 0',
        'params': {'a': 1.0},
        'domain': {'x': (0, 1), 't': (0, 1)},
        'ic_expression': 'exp(-50*(x-0.3)**2)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': 'u(x,t)=u_0(x-at)',
        'difficulty': '⭐⭐',
        'default_epochs': 5000,
        'default_layers': [2, 128, 128, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'black_scholes',
        'name': 'Black-Scholes方程',
        'pde_type': 'black_scholes',
        'n_dims': 1,
        'category': '数理金融',
        'description': '金融数学欧式期权定价方程',
        'equation_latex': r'\frac{\partial V}{\partial t}+\frac{1}{2}\sigma^2 S^2 \frac{\partial^2 V}{\partial S^2}+rS\frac{\partial V}{\partial S}-rV=0',
        'params': {'r': 0.05, 'sigma': 0.2, 'K': 100.0},
        'domain': {'x': (50, 150), 't': (0, 1)},
        'ic_expression': 'max(K - S, 0)',
        'bc_left_expression': 'max(K - x_min, 0)',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': '欧式看跌期权闭式解',
        'difficulty': '⭐⭐⭐',
        'default_epochs': 5000,
        'default_layers': [2, 128, 128, 64, 1],
        'has_fdm_reference': False,
    },
    {
        'id': 'laplace_2d',
        'name': '2D拉普拉斯方程',
        'pde_type': 'laplace',
        'n_dims': 2,
        'category': '椭圆型',
        'description': '无势场的2D拉普拉斯方程',
        'equation_latex': r'\Delta u = 0',
        'params': {},
        'domain': {'x': (0, 1), 'y': (0, 1), 't': (0, 1)},
        'ic_expression': '0',
        'bc_left_expression': '0',
        'bc_right_expression': 'sin(pi*y)',
        'bc_bottom_expression': '0',
        'bc_top_expression': 'sin(pi*x)',
        'analytical_solution': True,
        'reference_solution': '分离变量法解',
        'difficulty': '⭐⭐',
        'default_epochs': 5000,
        'default_layers': [3, 64, 128, 64, 1],
        'has_fdm_reference': True,
    },
    {
        'id': 'cahn_hilliard',
        'name': 'Cahn-Hilliard方程',
        'pde_type': 'cahn_hilliard',
        'n_dims': 1,
        'category': '相场方程',
        'description': '四阶PDE，描述合金相分离',
        'equation_latex': r'\frac{\partial u}{\partial t} = \gamma \Delta (\varepsilon^2 \Delta u - u^3 + u)',
        'params': {'epsilon': 0.01, 'gamma': 1.0},
        'domain': {'x': (0, 1), 't': (0, 1)},
        'ic_expression': '0.1*sin(2*pi*x)+0.5*cos(4*pi*x)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': False,
        'reference_solution': '',
        'difficulty': '⭐⭐⭐⭐⭐',
        'default_epochs': 20000,
        'default_layers': [2, 256, 512, 256, 1],
        'has_fdm_reference': False,
    },
    {
        'id': 'heat_2d',
        'name': '2D热传导方程',
        'pde_type': 'heat',
        'n_dims': 2,
        'category': '抛物型',
        'description': '二维空间瞬态热传导',
        'equation_latex': r'u_t = \alpha (u_{xx}+u_{yy})',
        'params': {'alpha': 0.01},
        'domain': {'x': (0, 1), 'y': (0, 1), 't': (0, 1)},
        'ic_expression': 'sin(pi*x)*sin(pi*y)',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'analytical_solution': True,
        'reference_solution': 'u=sin(πx)sin(πy)·exp(-2απ²t)',
        'difficulty': '⭐⭐⭐',
        'default_epochs': 10000,
        'default_layers': [3, 128, 256, 128, 1],
        'has_fdm_reference': False,
    },
    {
        'id': 'ns_lid_cavity',
        'name': '顶盖驱动方腔流(2D NS)',
        'pde_type': 'ns_incompressible',
        'n_dims': 2,
        'category': '计算流体力学',
        'description': '经典CFD算例，不可压缩Navier-Stokes',
        'equation_latex': r'\rho(\mathbf{u}_t+\mathbf{u}\cdot\nabla\mathbf{u})=-\nabla p+\mu\nabla^2\mathbf{u}, \nabla\cdot\mathbf{u}=0',
        'params': {'nu': 0.01, 'rho': 1.0},
        'domain': {'x': (0, 1), 'y': (0, 1), 't': (0, 1)},
        'ic_expression': '0',
        'bc_left_expression': '0',
        'bc_right_expression': '0',
        'bc_bottom_expression': '0',
        'bc_top_expression': '1',
        'analytical_solution': False,
        'reference_solution': '文献基准解(Re=100)',
        'difficulty': '⭐⭐⭐⭐⭐',
        'default_epochs': 30000,
        'default_layers': [3, 256, 512, 512, 256, 3],
        'has_fdm_reference': False,
    },
]


def get_library_index():
    """返回案例库索引（精简版，不含函数参数）"""
    index = []
    for case in PDE_LIBRARY:
        idx = {
            'id': case['id'],
            'name': case['name'],
            'pde_type': case['pde_type'],
            'n_dims': case['n_dims'],
            'category': case['category'],
            'description': case['description'],
            'equation_latex': case['equation_latex'],
            'difficulty': case['difficulty'],
            'analytical_solution': case['analytical_solution'],
            'reference_solution': case['reference_solution'],
            'has_fdm_reference': case['has_fdm_reference'],
        }
        index.append(idx)
    return index


def get_case(case_id):
    """根据ID获取完整案例"""
    for c in PDE_LIBRARY:
        if c['id'] == case_id:
            return c
    return None


def create_case_functions(case, params_override=None):
    """根据案例创建IC/BC函数"""
    from pinn_solver_nd import create_ic_func_nd
    spatial_keys = ['x', 'y', 'z'][:case.get('n_dims', 1)]
    if params_override:
        params = {**case['params'], **params_override}
    else:
        params = case['params']

    ic_fn = create_ic_func_nd(case['ic_expression'], params, spatial_keys)
    bc_fns = []
    for dim, k in enumerate(spatial_keys):
        left_key = 'bc_left_expression' if dim == 0 else f'bc_{spatial_keys[dim-1]}_left_expression'
        if dim == 0:
            lk, rk = 'bc_left_expression', 'bc_right_expression'
        elif dim == 1:
            lk, rk = 'bc_bottom_expression', 'bc_top_expression'
        else:
            lk, rk = 'bc_zmin_expression', 'bc_zmax_expression'
        bc_fns.append(create_ic_func_nd(case.get(lk, '0'), params, ['t']))
        bc_fns.append(create_ic_func_nd(case.get(rk, '0'), params, ['t']))

    return ic_fn, bc_fns
